# SPDX-FileCopyrightText: Copyright (c) 2025 Niladri Das <bniladridas>
# SPDX-License-Identifier: MIT
---
# Composite Action: Handle Release
# This action automates the release process: version bumping, PR creation,
# tagging, and GitHub release publishing.

name: 'Handle Release'
description: 'Bump version, create PR, tag, and release'
inputs:
  token:
    description: GitHub token for API access
    required: true
runs:
  using: 'composite'
  steps:
    - name: Bump version
      run: |
        current=$(cat VERSION)
        new=$(echo $current | awk -F. '{print $1"."$2"."($3+1)}')
        echo $new > VERSION
        sed -i "s/__version__ = \"$current\"/__version__ = \"$new\"/" vortai/__init__.py
        sed -i "s/version = \"$current\"/version = \"$new\"/" pyproject.toml
        echo "CURRENT_VERSION=$current" >> $GITHUB_ENV
        echo "NEW_VERSION=$new" >> $GITHUB_ENV
      shell: bash
    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        branch: automated/version-bump
        title: "Automated version bump"
        body: |
          This PR bumps the version for a new release.

          - Increments patch version
          - Updates VERSION, __init__.py, pyproject.toml
        commit-message: "chore: bump version"
        labels: |
          automated
          version-bump
    - name: Create tag
      run: |
        if ! git ls-remote --tags origin | grep -q "refs/tags/v${{ env.NEW_VERSION }}"; then
          git tag v${{ env.NEW_VERSION }} && git push origin v${{ env.NEW_VERSION }}
        fi
      shell: bash
    - name: Generate release notes
      run: |
        notes=$(git log --oneline --pretty=format:"- %s" HEAD~1..HEAD | grep -v "fix: pre-commit" | grep -v "feat: add pre-commit")
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        echo "## Automated release v${{ env.NEW_VERSION }}" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "### Changes" >> $GITHUB_ENV
        echo "$notes" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo "### Features" >> $GITHUB_ENV
        echo "- Multi-language AI platform (Python, Rust, Go, TypeScript, Cython)" >> $GITHUB_ENV
        echo "- Async operations and caching" >> $GITHUB_ENV
        echo "- Security hardening" >> $GITHUB_ENV
        echo "- CI/CD automation" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.NEW_VERSION }}
        name: Release v${{ env.NEW_VERSION }}
        body: ${{ env.RELEASE_NOTES }}
        draft: false
        prerelease: false
